#!/usr/bin/env python3.6

user = { 'admin' : True, 'active' : True, 'name': 'Kevin'}
placeholder = ""

if user['admin']:
        placeholder = "(ADMIN) "
elif user['active']:
        placeholder = "ACTIVE -"
elif user['admin'] and  user['active']:
        placeholder = "ACTIVE - (ADMIN) "

print(placeholder + user['name'])
