#!/usr/bin/env python3.6

first_name = "Max "
last_name = "Maddman"
age = 37
birth_date = "07/19/1998"

print(f"My name is {first_name}  {last_name}.")
print(f"I was born on {birth_date} , and I'm {age} years old.")
